# Generated by Django 3.2.6 on 2022-02-24 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0049_alter_yolo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetsonNano',
            fields=[
                ('id', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(0, 'connected'), (1, 'disconnect'), (2, 'unknown')], default=2)),
                ('timestamp', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JetsonNano',
            },
        ),
    ]
