# Generated by Django 3.2.6 on 2022-03-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0051_auto_20220304_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetsonnano',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='JetsonNano/'),
        ),
    ]
