# Generated by Django 3.2.6 on 2022-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot', '0007_auto_20211120_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertimagenotification',
            name='continuous_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='continuous_alert',
            field=models.BooleanField(default=False),
        ),
    ]
