version: "3.7"

services:
  ngrok:
    image: app_1:1.2
    command: sh -c "python ngrok/run_ngrok.py"
    # volumes:
    #   - for_ai2021mis:/ai2021mis
    ports:
      - "8000:8000"


  ai2021mis:
    image: app_1:1.2
    ports:
      - "4000:8000"
    environment:
      - DEFAULT_REDIS_LOCATION_1= redis://redis:6379/1
      - DEFAULT_REDIS_LOCATION_2= redis://redis:6379/2
      - CELERY_BROKER_URL=redis://redis:6379/0
    # volumes:
    #   - for_ai2021mis:/ai2021mis
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver"

  redis:
    image: redis
    restart: always

  celery_worker:
    restart: always
    image: app_1:1.2
    command: sh -c "sleep 15 && celery -A ai2021mis worker -l info"
    # volumes:
    #   - for_ai2021mis:/ai2021mis
    environment:
      - DEFAULT_REDIS_LOCATION_1= redis://redis:6379/1
      - DEFAULT_REDIS_LOCATION_2= redis://redis:6379/2
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - ai2021mis
      - redis

  celery_flower:
    restart: always
    image: app_1:1.2
    command: sh -c "sleep 15 && celery -A ai2021mis flower"
    # volumes:
    #   - for_ai2021mis:/ai2021mis
    environment:
      - DEFAULT_REDIS_LOCATION_1= redis://redis:6379/1
      - DEFAULT_REDIS_LOCATION_2= redis://redis:6379/2
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - ai2021mis
      - redis
      - celery_worker
    ports:
      - '5555:5555'

volumes:
  for_ai2021mis:
    external: true


