# Generated by Django 3.2.6 on 2022-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
