# Generated by Django 3.2.6 on 2022-03-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_employee_forgot_password_token'),
        ('employee', '0016_alter_employee_password'),
    ]

    operations = [
    ]
