# Generated by Django 3.2.6 on 2022-03-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20220307_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='3TYNlGnkvY', max_length=50),
        ),
    ]
