# Generated by Django 3.2.6 on 2022-03-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='wbxQVRk4ty', max_length=50),
        ),
    ]
