# Generated by Django 3.2.6 on 2022-03-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20220323_1435'),
        ('employee', '0020_alter_employee_password'),
    ]

    operations = [
    ]
