# Generated by Django 3.2.6 on 2022-04-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_merge_20220325_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='eWNr8WooIM', max_length=50),
        ),
    ]
