# Generated by Django 3.2.6 on 2022-04-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alert_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='UC4OPush04', max_length=50),
        ),
    ]
