# Generated by Django 3.2.6 on 2022-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20220412_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='continuous_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='sIgSlCSjI4', max_length=50),
        ),
    ]
