# Generated by Django 3.2.6 on 2022-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20220413_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='jNxfYg7j6v', max_length=50),
        ),
    ]
